workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60

    environment:
      groups:
        - android_credentials
      java: 17

    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
