workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      java: 17
      gradle: wrapper
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
